### ISSUE TITLE
Running with tens of thousands of ranks

### ISSUE THREAD

**Issue by bcaddy** [LLNL/gtest-mpi-listener#21]
Has there been any work on making this efficient with 50k+ MPI ranks? I think I'm going to need that functionality shortly.

**Comment by goxberry** [comment]
I haven't done any serious work on this project in a few years; most of it was set up over a few weekends to get basic functionality running quickly, and I've lagged a bit on responding to issues.

I think use cases at scale need a bit more information. Off the top of my head, some issues that come up at scale include:

* logging: gathering to rank 0 and writing to console isn't scalable, obviously. Other common I/O patterns have different tradeoffs; you may want to indicate your preferences for MPI requirements or sophistication versus efficiency.
* filtering: forcing users to read "PASSED" (or whatever denotes a successful test) for 50k+ ranks is probably silly; more terse representations are probably better. As for outputs on failure, it may make sense to have a verbosity level indicating how much information is provided on failure.
* API/semantics: the current implementation is intentionally minimal (IIRC...), in that MPI communicators and ranks aren't passed to test fixtures as arguments, and users are expected to write their own code to test, e.g., only on certain ranks. At scale, it probably makes more sense to have a more fully-featured API that provides mechanisms for passing in constructs like communicators, maybe subcommunicators/groups, possibly individual ranks. A more sophisticated API would probably make it easier to expose different options for logging or filtering.

The most I could do at the moment is provide suggestions and maybe do some design work. If there's enough of a user base, I might be able to make a case to write a proposal to fund some work on this project, but odds of getting the funding are slim.

**Comment by bcaddy** [comment]
Thank you. I think I'm going to try something simpler and see if I can get that to meet our needs before I dive into this.
